---
# Reference: https://www.gitpod.io/docs/references/gitpod-yml
tasks:
  - init: |
      pyenv install
      pyenv exec pip install --upgrade pip black

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - EditorConfig.EditorConfig
